#!/usr/bin/env bash
# One-command bootstrap for PilingTrack on a fresh machine.
# Generates secrets if missing, brings the full stack up via Docker
# (Postgres + Redis + app + workers + WebSocket), and waits for
# migration + seed to finish before printing credentials.

set -euo pipefail
cd "$(dirname "$0")"

echo
echo "============================================================"
echo " PilingTrack — first-run setup"
echo "============================================================"

# 1. Verify Docker.
if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker is not installed or not on PATH."
  echo "Install from https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' plugin is not available."
  echo "Update Docker to a recent version."
  exit 1
fi

# 2. Generate .env.docker if missing.
if [ ! -f .env.docker ]; then
  echo "Generating .env.docker with random secrets..."

  rand_hex() {
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  }

  rand_alphanum() {
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"
  }

  SESSION_SECRET=$(rand_hex 32)
  PIN_LOOKUP_SECRET=$(rand_hex 32)
  DEVICE_KEY_LOOKUP_SECRET=$(rand_hex 32)
  ENCRYPTION_KEY=$(rand_hex 32)
  POSTGRES_PASSWORD=$(rand_alphanum 24)
  PGADMIN_PASSWORD=$(rand_alphanum 16)

  cat > .env.docker <<EOF
# Auto-generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S').
# All secrets are unique per machine — do not commit this file.

# PostgreSQL
POSTGRES_USER=piling
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=pilingtrack
DATABASE_URL=postgresql://piling:${POSTGRES_PASSWORD}@postgres:5432/pilingtrack?schema=public
DATABASE_URL_POSTGRES=postgresql://piling:${POSTGRES_PASSWORD}@postgres:5432/pilingtrack?schema=public
DATABASE_PROVIDER=postgres
DATABASE_LOG_QUERIES=false

# Redis
REDIS_URL=redis://redis:6379

# Security secrets (32 bytes hex each)
SESSION_SECRET=${SESSION_SECRET}
PIN_LOOKUP_SECRET=${PIN_LOOKUP_SECRET}
DEVICE_KEY_LOOKUP_SECRET=${DEVICE_KEY_LOOKUP_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Multi-tenancy
MULTI_TENANT_MODE=single
DEFAULT_TENANT_ID=default

# WebSocket
WS_URL=ws://ws:3001
NEXT_PUBLIC_WS_URL=ws://localhost:3001

# Sentry / OpenTelemetry (blank = disabled)
SENTRY_ORG=
SENTRY_PROJECT=pilingtrack
SENTRY_AUTH_TOKEN=
OTEL_ENABLED=false

# pgAdmin (--profile dev)
PGADMIN_EMAIL=admin@pilingtrack.local
PGADMIN_PASSWORD=${PGADMIN_PASSWORD}

NODE_ENV=production
EOF
  echo "  - 32-byte secrets generated."
  echo "  - Postgres password: ${POSTGRES_PASSWORD}"
  echo "  - pgAdmin password:  ${PGADMIN_PASSWORD}"
else
  echo ".env.docker already exists — skipping secret generation."
fi

# 3. Bring up the stack.
echo
echo "Building and starting containers (first run takes 3-5 min)..."
docker compose --env-file .env.docker up -d --build

# 4. Wait for migrate to finish.
echo
echo "Waiting for database migrations + seed to complete..."
docker compose --env-file .env.docker logs -f migrate || true
docker compose --env-file .env.docker wait migrate >/dev/null 2>&1 || true

# 5. Done.
echo
echo "============================================================"
echo " PilingTrack is up."
echo
echo " App:        http://localhost:3000"
echo " WebSocket:  ws://localhost:3001"
echo " Postgres:   localhost:5432   (user: piling)"
echo " PgBouncer:  localhost:6432"
echo " Redis:      localhost:6379"
echo
echo " Default credentials (change after first login):"
echo "   admin:      admin@piling.ru     / admin123"
echo "   dispatcher: dispatch@piling.ru  / dispatch123"
echo "   operator:   operator@piling.ru  / operator123"
echo "   helper:     helper@piling.ru    / helper123"
echo
echo " Stop the stack:    docker compose --env-file .env.docker down"
echo " Reset everything:  docker compose --env-file .env.docker down -v"
echo "============================================================"
