-- Restore Report.journalPhotoMediaId.
--
-- The column was dropped unintentionally by 20260526202204_equipment_maintenance
-- (an autogenerated `prisma migrate dev` diff bundled an unrelated DROP COLUMN),
-- but schema.prisma still declares the field, so the deployed Prisma client
-- queries a column that no longer exists and every Report read/write fails.
--
-- Idempotent so it is a no-op where the column was already restored manually.

ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "journalPhotoMediaId" TEXT;
