import {chromium} from '@playwright/test';
const browser = await chromium.launch();
const ctx = await browser.newContext({storageState: 'e2e/operator-next/.auth/ka.json', baseURL: 'http://localhost:3210', viewport: {width: 375, height: 812}, hasTouch: true, isMobile: true});
const page = await ctx.newPage();
const seen = [];
page.on('request', (r) => { const u = r.url(); if (u.includes('/api/auth')) seen.push(r.method() + ' ' + u.replace('http://localhost:3210', '')); });
await page.goto('/operator/next', {waitUntil: 'domcontentloaded'});
await page.waitForTimeout(7000);
console.log('на /operator/next запросы /api/auth/*:'); console.log(seen.join('\n') || '  НИ ОДНОГО');
seen.length = 0;
await page.goto('/admin', {waitUntil: 'domcontentloaded'});
await page.waitForTimeout(7000);
console.log('на /admin запросы /api/auth/*:'); console.log(seen.join('\n') || '  ни одного');
await browser.close();