/**
 * Dead Letter Queue — Failed outbox events
 *
 * Events that exceed MAX_RETRIES are moved here for:
 * - Manual inspection
 * - Retry with debugging
 * - Alerting on persistent failures
 *
 * Usage:
 *   await deadLetterQueue.moveToDlq(event, error, attempts);
 *   await deadLetterQueue.retry(id);
 *   await deadLetterQueue.discard(id);
 *   const stats = await deadLetterQueue.getStats();
 */

import { db } from '@/lib/db';
import { logger } from '@/lib/logger';

export interface DlqEntry {
  id: string;
  eventType: string;
  aggregateId: string | null;
  payload: unknown;
  errorMessage: string;
  attempts: number;
  sourceOutboxId: string | null;
  createdAt: Date;
  updatedAt: Date;
  status: 'pending' | 'resolved' | 'discarded';
}

export async function moveToDlq(
  outboxId: string,
  eventType: string,
  aggregateId: string | null,
  payload: unknown,
  error: unknown,
  attempts: number
): Promise<void> {
  const errorMessage = error instanceof Error ? error.message : String(error);

  try {
    await db.deadLetterQueue.create({
      data: {
        eventType,
        aggregateId,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Prisma JSON column / event payload is an arbitrary serializable shape
        payload: payload as any,
        errorMessage: errorMessage.substring(0, 2000),
        attempts,
        sourceOutboxId: outboxId,
      },
    });

    // NOTE: Marking the source OutboxEvent as consumed is the caller's job
    // (consumeOutboxEvents sets its own consumer column atomically). Setting
    // published=false here used to re-queue the row forever — every tick
    // would re-fetch it, the handler would fail again, attempts would tick
    // past MAX_RETRIES, and moveToDlq would be called repeatedly, spamming
    // duplicates into DLQ. Now this function only writes to DLQ; the caller
    // claims the outbox row.

    logger.error('Event moved to Dead Letter Queue', {
      outboxId,
      eventType,
      aggregateId,
      attempts,
      errorMessage,
    });

    // Best-effort Telegram alert — never blocks the DLQ write.
    import('@/core/notifications/telegram').then(({ telegramNotifier }) => {
      void telegramNotifier.sendMessage(
        `⚠️ <b>Dead Letter Queue</b>\n\nСобытие <code>${eventType}</code> исчерпало ${attempts} попыток.\n` +
        (aggregateId ? `aggregateId: <code>${aggregateId}</code>\n` : '') +
        `Ошибка: <code>${errorMessage.substring(0, 200)}</code>`
      ).catch(() => {/* ignore */});
    }).catch(() => {/* ignore */});
  } catch (dlqError) {
    // Last resort — log to console
    logger.error('DLQ: failed to move event to DLQ', dlqError);
  }
}

export async function retryDlqEntry(id: string): Promise<boolean> {
  const entry = await db.deadLetterQueue.findUnique({ where: { id } });
  if (!entry) return false;
  // Idempotency guard: already processed (resolved/discarded) — don't re-queue.
  if (entry.status !== 'pending') return false;

  try {
    // Do NOT reuse entry.id — that's the DLQ id, not the original outbox id.
    // Reusing it would cause P2002 on a second retry attempt before the page refreshes.
    // A new CUID is generated by default (no `id` field = Prisma generates one).
    await db.outboxEvent.create({
      data: {
        type: entry.eventType,
        aggregateId: entry.aggregateId ?? 'unknown',
        aggregateType: 'Report',
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Prisma JSON column / event payload is an arbitrary serializable shape
        payload: entry.payload as any,
        attempts: 0,
        published: false,
      },
    });

    await db.deadLetterQueue.update({
      where: { id },
      data: { status: 'resolved' },
    });

    return true;
  } catch (err) {
    logger.error('DLQ retry failed', { id, error: err });
    return false;
  }
}

export async function discardDlqEntry(id: string): Promise<void> {
  await db.deadLetterQueue.update({
    where: { id },
    data: { status: 'discarded' },
  });
}

export async function getDlqStats(): Promise<{
  pending: number;
  resolved: number;
  discarded: number;
  total: number;
}> {
  const [pending, resolved, discarded] = await Promise.all([
    db.deadLetterQueue.count({ where: { status: 'pending' } }),
    db.deadLetterQueue.count({ where: { status: 'resolved' } }),
    db.deadLetterQueue.count({ where: { status: 'discarded' } }),
  ]);

  return { pending, resolved, discarded, total: pending + resolved + discarded };
}

export async function getPendingDlqEntries(limit: number = 100): Promise<DlqEntry[]> {
  const rows = await db.deadLetterQueue.findMany({
    where: { status: 'pending' },
    orderBy: { createdAt: 'asc' },
    take: limit,
  });
  return rows.map((row) => ({
    id: row.id,
    eventType: row.eventType,
    aggregateId: row.aggregateId,
    payload: row.payload,
    errorMessage: row.errorMessage,
    attempts: row.attempts,
    sourceOutboxId: row.sourceOutboxId,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    status: row.status as DlqEntry['status'],
  }));
}
