# Generate .env.docker (for Docker stack) AND .env (for local npm dev) with
# matching cryptographically random secrets. Called by setup.bat on first run.
#
# Both files share the same Postgres password / SESSION_SECRET / ENCRYPTION_KEY
# so local `npm run dev` and Docker containers can both use the same database
# and decrypt the same secrets (e.g. Telegram bot tokens).

$ErrorActionPreference = 'Stop'

function New-Secret {
  param([int]$Bytes = 32)
  $buffer = New-Object byte[] $Bytes
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    $rng.Dispose()
  }
  ($buffer | ForEach-Object { $_.ToString('x2') }) -join ''
}

$sessionSecret = New-Secret 32
$pinSecret     = New-Secret 32
$deviceSecret  = New-Secret 32
$encryptionKey = New-Secret 32
$pgPassword    = New-Secret 16
$pgadminPass   = New-Secret 12

# ============================================================
# .env.docker — used by `docker compose --env-file .env.docker`
# Hosts use Docker DNS (postgres, redis, ws).
# ============================================================
$dockerContent = @"
# Auto-generated by setup.bat on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
# All secrets are unique per machine - do not commit this file.

# ============================================================
# PostgreSQL
# ============================================================
POSTGRES_USER=piling
POSTGRES_PASSWORD=$pgPassword
POSTGRES_DB=pilingtrack
DATABASE_URL=postgresql://piling:$pgPassword@postgres:5432/pilingtrack?schema=public
DATABASE_URL_POSTGRES=postgresql://piling:$pgPassword@postgres:5432/pilingtrack?schema=public
DATABASE_PROVIDER=postgres
DATABASE_LOG_QUERIES=false

# ============================================================
# Redis
# ============================================================
REDIS_URL=redis://redis:6379

# ============================================================
# Security secrets (32 bytes hex each)
# ============================================================
SESSION_SECRET=$sessionSecret
PIN_LOOKUP_SECRET=$pinSecret
DEVICE_KEY_LOOKUP_SECRET=$deviceSecret
ENCRYPTION_KEY=$encryptionKey

# ============================================================
# Multi-tenancy
# ============================================================
MULTI_TENANT_MODE=single
DEFAULT_TENANT_ID=default

# ============================================================
# WebSocket
# ============================================================
WS_URL=ws://ws:3001
NEXT_PUBLIC_WS_URL=ws://localhost:3001

# ============================================================
# S3 / MinIO (PDF storage)
# ============================================================
S3_ENDPOINT=http://minio:9000
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin
S3_BUCKET=pilingtrack-pdfs
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true

# ============================================================
# Sentry / OpenTelemetry (optional, blank = disabled)
# ============================================================
SENTRY_ORG=
SENTRY_PROJECT=pilingtrack
SENTRY_AUTH_TOKEN=
OTEL_ENABLED=false

# ============================================================
# pgAdmin (only used with --profile dev)
# ============================================================
PGADMIN_EMAIL=admin@pilingtrack.local
PGADMIN_PASSWORD=$pgadminPass

# ============================================================
# NODE_ENV
# ============================================================
NODE_ENV=production
"@

Set-Content -LiteralPath '.env.docker' -Value $dockerContent -Encoding utf8 -NoNewline

# ============================================================
# .env — used by local `npm run dev` / `npm run build`
# Hosts point at localhost (Docker port mappings).
# Same secrets as .env.docker so encrypted data is readable in both.
# ============================================================
$localContent = @"
# Auto-generated by setup.bat on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
# Used by local `npm run dev` against the Docker DB stack.

# ------------------------------------------------------------
# PostgreSQL (Docker port 5435 -> container 5432)
# ------------------------------------------------------------
DATABASE_URL=postgresql://piling:$pgPassword@localhost:5435/pilingtrack?schema=public
DATABASE_URL_POSTGRES=postgresql://piling:$pgPassword@localhost:5435/pilingtrack?schema=public
DATABASE_URL_PGBOUNCER=postgresql://piling:$pgPassword@localhost:6432/pilingtrack
DATABASE_PROVIDER=postgres
DATABASE_LOG_QUERIES=false

# ------------------------------------------------------------
# Redis (Docker port 6379)
# ------------------------------------------------------------
REDIS_URL=redis://localhost:6379

# ------------------------------------------------------------
# Security secrets (must match .env.docker so encrypted data
# in the DB is readable from both local npm and Docker stack).
# ------------------------------------------------------------
SESSION_SECRET=$sessionSecret
PIN_LOOKUP_SECRET=$pinSecret
DEVICE_KEY_LOOKUP_SECRET=$deviceSecret
ENCRYPTION_KEY=$encryptionKey

# ------------------------------------------------------------
# Multi-tenancy
# ------------------------------------------------------------
MULTI_TENANT_MODE=single
DEFAULT_TENANT_ID=default

# ------------------------------------------------------------
# WebSocket (use the dockerised ws service on localhost:3001
# OR run `npm run dev:ws` for a local instance).
# ------------------------------------------------------------
WS_URL=ws://localhost:3001
NEXT_PUBLIC_WS_URL=ws://localhost:3001

# ------------------------------------------------------------
# S3 / MinIO (Docker port 9000)
# ------------------------------------------------------------
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin
S3_BUCKET=pilingtrack-pdfs
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true

# ------------------------------------------------------------
# Misc
# ------------------------------------------------------------
NEXT_TELEMETRY_DISABLED=1
ASYNC_OUTBOX=true
NODE_ENV=development
"@

Set-Content -LiteralPath '.env' -Value $localContent -Encoding utf8 -NoNewline

Write-Host "  - 32-byte secrets generated (SESSION/PIN/DEVICE/ENCRYPTION)."
Write-Host "  - Postgres password: $pgPassword (saved to .env.docker + .env)"
Write-Host "  - pgAdmin password:  $pgadminPass (saved to .env.docker)"
Write-Host "  - .env.docker  -> Docker stack secrets (hosts: postgres, redis, ws)"
Write-Host "  - .env         -> local npm dev secrets (hosts: localhost:5435/6379/9000)"
