# Generate .env.docker with cryptographically random secrets.
# Called by setup.bat on first run.

$ErrorActionPreference = 'Stop'

function New-Secret {
  param([int]$Bytes = 32)
  $buffer = New-Object byte[] $Bytes
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    $rng.Dispose()
  }
  ($buffer | ForEach-Object { $_.ToString('x2') }) -join ''
}

$sessionSecret = New-Secret 32
$pinSecret     = New-Secret 32
$deviceSecret  = New-Secret 32
$encryptionKey = New-Secret 32
$pgPassword    = New-Secret 16
$pgadminPass   = New-Secret 12

$content = @"
# Auto-generated by setup.bat on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
# All secrets are unique per machine — do not commit this file.

# ============================================================
# PostgreSQL
# ============================================================
POSTGRES_USER=piling
POSTGRES_PASSWORD=$pgPassword
POSTGRES_DB=pilingtrack
DATABASE_URL=postgresql://piling:$pgPassword@postgres:5432/pilingtrack?schema=public
DATABASE_URL_POSTGRES=postgresql://piling:$pgPassword@postgres:5432/pilingtrack?schema=public
DATABASE_PROVIDER=postgres
DATABASE_LOG_QUERIES=false

# ============================================================
# Redis
# ============================================================
REDIS_URL=redis://redis:6379

# ============================================================
# Security secrets (32 bytes hex each)
# ============================================================
SESSION_SECRET=$sessionSecret
PIN_LOOKUP_SECRET=$pinSecret
DEVICE_KEY_LOOKUP_SECRET=$deviceSecret
ENCRYPTION_KEY=$encryptionKey

# ============================================================
# Multi-tenancy
# ============================================================
MULTI_TENANT_MODE=single
DEFAULT_TENANT_ID=default

# ============================================================
# WebSocket
# ============================================================
WS_URL=ws://ws:3001
NEXT_PUBLIC_WS_URL=ws://localhost:3001

# ============================================================
# Sentry / OpenTelemetry (optional, blank = disabled)
# ============================================================
SENTRY_ORG=
SENTRY_PROJECT=pilingtrack
SENTRY_AUTH_TOKEN=
OTEL_ENABLED=false

# ============================================================
# pgAdmin (only used with --profile dev)
# ============================================================
PGADMIN_EMAIL=admin@pilingtrack.local
PGADMIN_PASSWORD=$pgadminPass

# ============================================================
# NODE_ENV
# ============================================================
NODE_ENV=production
"@

Set-Content -LiteralPath '.env.docker' -Value $content -Encoding utf8 -NoNewline
Write-Host "  - 32-byte secrets generated for SESSION/PIN/DEVICE/ENCRYPTION."
Write-Host "  - Postgres password: $pgPassword (saved to .env.docker)"
Write-Host "  - pgAdmin password:  $pgadminPass (saved to .env.docker)"
