apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pilingtrack-ingress
  namespace: pilingtrack-prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: app.pilingtrack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pilingtrack-prod-api
                port:
                  number: 3000
    - host: ws.pilingtrack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pilingtrack-prod-websocket
                port:
                  number: 4000
