{{- if or .Values.secrets.databaseUrl .Values.secrets.redisUrl .Values.secrets.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilingtrack.fullname" . }}-secrets
  labels:
    {{- include "pilingtrack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL_POSTGRES: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.sessionSecret }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.encryptionKey }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.s3AccessKey }}
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.s3SecretKey }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.sentryAuthToken }}
  SENTRY_AUTH_TOKEN: {{ .Values.secrets.sentryAuthToken | quote }}
  {{- end }}
{{- end }}
